"""Add column image to the news table

Revision ID: 90996cba2b07
Revises: 384a2d961434
Create Date: 2025-02-19 14:39:22.307147

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "90996cba2b07"
down_revision: Union[str, None] = "384a2d961434"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("news", sa.Column("image", postgresql.BYTEA(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news", "image")
    # ### end Alembic commands ###
