"""add fcm_token_table

Revision ID: 1b5f3e57b584
Revises: 7c3bf5ee0169
Create Date: 2025-05-05 18:19:06.748474

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b5f3e57b584"
down_revision: Union[str, None] = "7c3bf5ee0169"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fcm_tokens",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("fcm_tokens_pkey")),
    )
    op.create_index(op.f("fcm_tokens_id_idx"), "fcm_tokens", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("fcm_tokens_id_idx"), table_name="fcm_tokens")
    op.drop_table("fcm_tokens")
    # ### end Alembic commands ###
