"""Add roles table

Revision ID: 7c3bf5ee0169
Revises: c8a74eb079a7
Create Date: 2025-04-28 10:39:55.228976

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c3bf5ee0169"
down_revision: Union[str, None] = "c8a74eb079a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("can_edit_news", sa.Boolean(), nullable=False),
        sa.Column("can_edit_categories", sa.Boolean(), nullable=False),
        sa.Column("can_edit_admins", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("roles_pkey")),
    )
    op.create_index(op.f("roles_id_idx"), "roles", ["id"], unique=False)
    op.add_column("users", sa.Column("role_id", sa.Integer(), nullable=False))
    op.create_foreign_key(op.f("users_role_id_fkey"), "users", "roles", ["role_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_role_id_fkey"), "users", type_="foreignkey")
    op.drop_column("users", "role_id")
    op.drop_index(op.f("roles_id_idx"), table_name="roles")
    op.drop_table("roles")
    # ### end Alembic commands ###
